CREATE TABLE "food" (
	"food_code" text PRIMARY KEY NOT NULL,
	"food_name" text NOT NULL,
	"primerysource" text NOT NULL,
	"energy_kj" real NOT NULL,
	"energy_kcal" real NOT NULL,
	"protein_g" real NOT NULL,
	"carb_g" real NOT NULL,
	"fat_g" real NOT NULL,
	"image" text
);
--> statement-breakpoint
CREATE TABLE "food_metadata" (
	"food_code" text NOT NULL,
	"freesugar_g" real,
	"fibre_g" real,
	"sfa_mg" real,
	"mufa_mg" real,
	"pufa_mg" real,
	"cholesterol_mg" real,
	"calcium_mg" real,
	"phosphorus_mg" real,
	"magnesium_mg" real,
	"sodium_mg" real,
	"potassium_mg" real,
	"iron_mg" real,
	"copper_mg" real,
	"selenium_ug" real,
	"chromium_mg" real,
	"manganese_mg" real,
	"molybdenum_mg" real,
	"zinc_mg" real,
	"vita_ug" real,
	"vite_mg" real,
	"vitd2_ug" real,
	"vitd3_ug" real,
	"vitk1_ug" real,
	"vitk2_ug" real,
	"folate_ug" real,
	"vitb1_mg" real,
	"vitb2_mg" real,
	"vitb3_mg" real,
	"vitb5_mg" real,
	"vitb6_mg" real,
	"vitb7_ug" real,
	"vitb9_ug" real,
	"vitc_mg" real,
	"carotenoids_ug" real,
	"servings_unit" text,
	"unit_serving_energy_kj" real,
	"unit_serving_energy_kcal" real,
	"unit_serving_carb_g" real,
	"unit_serving_protein_g" real,
	"unit_serving_fat_g" real,
	"unit_serving_freesugar_g" real,
	"unit_serving_fibre_g" real,
	"unit_serving_sfa_mg" real,
	"unit_serving_mufa_mg" real,
	"unit_serving_pufa_mg" real,
	"unit_serving_cholesterol_mg" real,
	"unit_serving_calcium_mg" real,
	"unit_serving_phosphorus_mg" real,
	"unit_serving_magnesium_mg" real,
	"unit_serving_sodium_mg" real,
	"unit_serving_potassium_mg" real,
	"unit_serving_iron_mg" real,
	"unit_serving_copper_mg" real,
	"unit_serving_selenium_ug" real,
	"unit_serving_chromium_mg" real,
	"unit_serving_manganese_mg" real,
	"unit_serving_molybdenum_mg" real,
	"unit_serving_zinc_mg" real,
	"unit_serving_vita_ug" real,
	"unit_serving_vite_mg" real,
	"unit_serving_vitd2_ug" real,
	"unit_serving_vitd3_ug" real,
	"unit_serving_vitk1_ug" real,
	"unit_serving_vitk2_ug" real,
	"unit_serving_folate_ug" real,
	"unit_serving_vitb1_mg" real,
	"unit_serving_vitb2_mg" real,
	"unit_serving_vitb3_mg" real,
	"unit_serving_vitb5_mg" real,
	"unit_serving_vitb6_mg" real,
	"unit_serving_vitb7_ug" real,
	"unit_serving_vitb9_ug" real,
	"unit_serving_vitc_mg" real,
	"unit_serving_carotenoids_ug" real
);
--> statement-breakpoint
ALTER TABLE "food_metadata" ADD CONSTRAINT "food_metadata_food_code_food_food_code_fk" FOREIGN KEY ("food_code") REFERENCES "public"."food"("food_code") ON DELETE cascade ON UPDATE no action;