DROP TABLE "food_metadata" CASCADE;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "freesugar_g" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "fibre_g" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "sfa_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "mufa_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "pufa_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "cholesterol_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "calcium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "phosphorus_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "magnesium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "sodium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "potassium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "iron_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "copper_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "selenium_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "chromium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "manganese_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "molybdenum_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "zinc_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vita_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vite_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitd2_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitd3_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitk1_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitk2_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "folate_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitb1_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitb2_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitb3_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitb5_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitb6_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitb7_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitb9_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "vitc_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "carotenoids_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "servings_unit" text;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_energy_kj" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_energy_kcal" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_carb_g" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_protein_g" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_fat_g" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_freesugar_g" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_fibre_g" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_sfa_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_mufa_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_pufa_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_cholesterol_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_calcium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_phosphorus_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_magnesium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_sodium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_potassium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_iron_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_copper_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_selenium_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_chromium_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_manganese_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_molybdenum_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_zinc_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vita_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vite_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitd2_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitd3_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitk1_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitk2_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_folate_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitb1_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitb2_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitb3_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitb5_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitb6_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitb7_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitb9_ug" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_vitc_mg" real;--> statement-breakpoint
ALTER TABLE "food" ADD COLUMN "unit_serving_carotenoids_ug" real;--> statement-breakpoint
ALTER TABLE "food" DROP COLUMN "image";